// converting preload to es module breaks the app
const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('versions', {
  node: () => process.versions.node,
  chrome: () => process.versions.chrome,
  electron: () => process.versions.electron,
  platform: () => process.platform
  // we can also expose variables, not just functions
})

contextBridge.exposeInMainWorld('api', {
  article: {
    create:            (article)            => ipcRenderer.invoke('article/create', article),
    updateMainText:    (id, newMainText)    => ipcRenderer.invoke('article/updateMainText', id, newMainText),
    updateExplanation: (id, newExplanation) => ipcRenderer.invoke('article/updateExplanation', id, newExplanation),
    updateComment:     (id, newComment)     => ipcRenderer.invoke('article/updateComment', id, newComment),
    updateTitle:       (id, newtitle)       => ipcRenderer.invoke('article/updateTitle', id, newtitle),
    updateOwner:       (id, newOwnerName)   => ipcRenderer.invoke('article/updateOwner', id, newOwnerName),
    updateCategory:    (id, newCategoryName)=> ipcRenderer.invoke('article/updateCategory', id, newCategoryName),
    updateDate:        (id, newDate)        => ipcRenderer.invoke('article/updateDate', id, newDate),
    updateDate2:       (id, newDate)        => ipcRenderer.invoke('article/updateDate2', id, newDate),
    addImage:          (id, image)          => ipcRenderer.invoke('article/addImage', id, image),
    openDialogToAddImages: (id)              => ipcRenderer.invoke('article/openDialogToAddImages', id),
    addAudio:          (id, audio)          => ipcRenderer.invoke('article/addAudio', id, audio),
    openDialogToAddAudios: (id)              => ipcRenderer.invoke('article/openDialogToAddAudios', id),
    addVideo:          (id, video)          => ipcRenderer.invoke('article/addVideo', id, video),
    openDialogToAddVideos: (id)              => ipcRenderer.invoke('article/openDialogToAddVideos', id),
    exportArticle: (exportData)              => ipcRenderer.invoke('article/exportArticle', exportData),
    addAnnotation:     (id, annotation)     => ipcRenderer.invoke('article/addAnnotation', id, annotation),
    getAll:            (order)              => ipcRenderer.invoke('article/getAll', order),
    getById:           (id)                 => ipcRenderer.invoke('article/getById', id),
    deleteById:        (id)                 => ipcRenderer.invoke('article/deleteById', id),
    addRelatedArticle: (id, relatedArticleId) => ipcRenderer.invoke('article/addRelatedArticle', id, relatedArticleId),
    removeRelatedArticle: (id, relatedArticleId) => ipcRenderer.invoke('article/removeRelatedArticle', id, relatedArticleId),
    addTag:           (id, tagName)           => ipcRenderer.invoke('article/addTag', id, tagName),
    removeTag:        (id, tagName)           => ipcRenderer.invoke('article/removeTag', id, tagName),
    addToGroup:       (id, groupName)         => ipcRenderer.invoke('article/addToGroup', id, groupName),
    removeFromGroup:  (id, groupId)           => ipcRenderer.invoke('article/removeFromGroup', id, groupId),
    setIsStarred:     (id, isStarred)         => ipcRenderer.invoke('article/setIsStarred', id, isStarred),
    setIsDateUncertain:     (id, isDateUncertain)         => ipcRenderer.invoke('article/setIsDateUncertain', id, isDateUncertain),
    setOrdering:     (id, ordering)         => ipcRenderer.invoke('article/setOrdering', id, ordering),
  },
  owner: {
    create:      (owner)        => ipcRenderer.invoke('owner/create', owner),
    updateName:  (id, newName)  => ipcRenderer.invoke('owner/updateName', id, newName),
    getAll:      ()             => ipcRenderer.invoke('owner/getAll'),
    getById:     (id)           => ipcRenderer.invoke('owner/getById', id),
    deleteById:  (id)           => ipcRenderer.invoke('owner/deleteById', id),
  },
  category: {
    create:      (id)           => ipcRenderer.invoke('category/create', id),
    updateName:  (id, newName)  => ipcRenderer.invoke('category/updateName', id, newName),
    updateColor: (id, newColor) => ipcRenderer.invoke('category/updateColor', id, newColor),
    getAll:      ()             => ipcRenderer.invoke('category/getAll'),
    getById:     (id)           => ipcRenderer.invoke('category/getById', id),
    deleteById:  (id)           => ipcRenderer.invoke('category/deleteById', id),
  },
  group: {
    create:      (id)           => ipcRenderer.invoke('group/create', id),
    updateName:  (id, newName)  => ipcRenderer.invoke('group/updateName', id, newName),
    getAll:      ()             => ipcRenderer.invoke('group/getAll'),
    getById:     (id)           => ipcRenderer.invoke('group/getById', id),
    addArticles: (groupName, articleIds) => ipcRenderer.invoke('group/addArticles', groupName, articleIds),
    deleteById:  (id)           => ipcRenderer.invoke('group/deleteById', id),
  },
  comment: {
    updateText: (id, newText) => ipcRenderer.invoke('comment/updateText', id, newText),
    getById:    (id)          => ipcRenderer.invoke('comment/getById', id),
  },
  image: {
    getDataById:   (id)     => ipcRenderer.invoke('image/getDataById', id),
    getDataByPath: (image)  => ipcRenderer.invoke('image/getDataByPath', image),
    getDataByAnyPath: (path, type) => ipcRenderer.invoke('image/getDataByAnyPath', path, type),
    deleteById:    (id)     => ipcRenderer.invoke('image/deleteById', id),
    download:      (id)     => ipcRenderer.invoke('image/download', id),
  },
  audio: {
    getDataById:   (id)     => ipcRenderer.invoke('audio/getDataById', id),
    getDataByPath: (path)   => ipcRenderer.invoke('audio/getDataByPath', path),
    deleteById:    (id)     => ipcRenderer.invoke('audio/deleteById', id),
    download:      (id)     => ipcRenderer.invoke('audio/download', id),
    extractMetadata: (id)   => ipcRenderer.invoke('audio/extractMetadata', id),
    updateMetadata: (id, metadata) => ipcRenderer.invoke('audio/updateMetadata', id, metadata),
    updateMissingDurations: () => ipcRenderer.invoke('audio/updateMissingDurations'),
  },
  video: {
    getDataById:   (id)     => ipcRenderer.invoke('video/getDataById', id),
    getDataByPath: (path)   => ipcRenderer.invoke('video/getDataByPath', path),
    deleteById:    (id)     => ipcRenderer.invoke('video/deleteById', id),
    download:      (id)     => ipcRenderer.invoke('video/download', id),
    extractMetadata: (id)   => ipcRenderer.invoke('video/extractMetadata', id),
    updateMetadata: (id, metadata) => ipcRenderer.invoke('video/updateMetadata', id, metadata),
    updateMissingDurations: () => ipcRenderer.invoke('video/updateMissingDurations'),
  },
  tag: {
    create:     (tag) => ipcRenderer.invoke('tag/create', tag),
    getAll:     () => ipcRenderer.invoke('tag/getAll'),
    getById:    (id) => ipcRenderer.invoke('tag/getById', id),
    updateName: (id, newName) => ipcRenderer.invoke('tag/updateName', id, newName),
    deleteById: (id) => ipcRenderer.invoke('tag/deleteById', id),
  },
  annotation: {
    deleteById:       (annotationId)          => ipcRenderer.invoke('annotation/deleteById', annotationId),
    getAll:           ()                      => ipcRenderer.invoke('annotation/getAll'),
    getById:          (annotationId)          => ipcRenderer.invoke('annotation/getById', annotationId),
    updateNote:       (annotationId, newNote) => ipcRenderer.invoke('annotation/updateNote', annotationId, newNote),
  },
  db: {
    loadArticles: () => ipcRenderer.invoke('DB/loadArticles'),
    loadArticlesFromTxt: () => ipcRenderer.invoke('DB/loadArticlesFromTxt'),
    handleExport: () => ipcRenderer.invoke('DB/handleExport'),
    handleImport: () => ipcRenderer.invoke('DB/handleImport'),
    handleBackup: () => ipcRenderer.invoke('DB/handleBackup'),
    changeBackupDir: () => ipcRenderer.invoke('DB/changeBackupDir'),
    getBackupDir: () => ipcRenderer.invoke('DB/getBackupDir'),
  },
  lookup: {
    create: (lookup) => ipcRenderer.invoke('lookup/create', lookup),
    getByLabel: (label) => ipcRenderer.invoke('lookup/getByLabel', label),
    updateValue: (label, newValue) => ipcRenderer.invoke('lookup/updateValue', label, newValue),
    setLastActiveDateToToday: () => ipcRenderer.invoke('lookup/setLastActiveDateToToday'),
  },
  store: {
    set: (key, value) => ipcRenderer.invoke('store/set', key, value),
    get: (key) => ipcRenderer.invoke('store/get', key),
  },
  getOwnerWithName:          (ownerName)   => ipcRenderer.invoke('getOwnerWithName', ownerName),
  getOwnerWithNameLike:      (nameLike)    => ipcRenderer.invoke('getOwnerWithNameLike', nameLike),
  ping:                      ()            => ipcRenderer.invoke('ping'),
  getFromDb:                 ()            => ipcRenderer.invoke('getFromDb'),
  checkDbConnection:         ()            => ipcRenderer.invoke('checkDbConnection'),
  addOwnerAndArticle:        ()            => ipcRenderer.invoke('addOwnerAndArticle'),
  deleteOwnerWithName:       (ownerName)   => ipcRenderer.invoke('deleteOwnerWithName', ownerName),
  getArticleWithTitleLike:   (titleLike)   => ipcRenderer.invoke('getArticleWithTitleLike', titleLike),
  getAllArticlesOfOwnerName: (ownerName)   => ipcRenderer.invoke('getAllArticlesOfOwnerName', ownerName),
})
